dist: xenial
language: python

matrix:
  include:
    - { python: "2.7", env: TOXENV=py27-dj111  }

    - { python: "3.5", env: TOXENV=py35-dj111 }
    - { python: "3.5", env: TOXENV=py35-dj20  }
    - { python: "3.5", env: TOXENV=py35-dj21  }
    - { python: "3.5", env: TOXENV=py35-dj22  }
    - { python: "3.5", env: TOXENV=py35-dj30  }

    - { python: "3.6", env: TOXENV=py36-dj111 }
    - { python: "3.6", env: TOXENV=py36-dj20  }
    - { python: "3.6", env: TOXENV=py36-dj21  }
    - { python: "3.6", env: TOXENV=py36-dj22  }
    - { python: "3.6", env: TOXENV=py36-dj30  }

    - { python: "3.7", env: TOXENV=py37-dj111 }
    - { python: "3.7", env: TOXENV=py37-dj20  }
    - { python: "3.7", env: TOXENV=py37-dj21  }
    - { python: "3.7", env: TOXENV=py37-dj22  }
    - { python: "3.7", env: TOXENV=py37-dj30  }

    - { python: "3.8", env: TOXENV=py38-dj111  }
    - { python: "3.8", env: TOXENV=py38-dj20   }
    - { python: "3.8", env: TOXENV=py38-dj21   }
    - { python: "3.8", env: TOXENV=py38-dj22   }
    - { python: "3.8", env: TOXENV=py38-dj30   }


env:
  global:
    - WEBDAV_URL="http://webdav-server.com/"
    - WEBDAV_PUBLIC_URL="http://webdav-server.com/"
    - WEBDAV_LISTING_BACKEND="django_webdav_storage.listing.nginx_autoindex"

install:
  - pip install -q tox tox-travis
  - python setup.py install

script:
  - tox

after_success:
  - coveralls
